version: '3.7'

services:
    mysql_container:
        image: mysql:5.7
        container_name: seriestv_mysql
        restart: always
        ports:
            - 33064:3306
        volumes:
            - ./data/mysql:/var/lib/mysql
            #- mysql_data:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=seriestv
            - MYSQL_USER=seriestv
            - MYSQL_PASSWORD=seriestv
            - MYSQL_ROOT_PASSWORD=seriestv
        # network_mode: host
#volumes:
#    mysql_data:
